delete from dbo.FirmaPageType
go

insert into dbo.FirmaPageType(FirmaPageTypeID, FirmaPageTypeName, FirmaPageTypeDisplayName, FirmaPageRenderTypeID)
values
(1, 'HomePage', 'Home Page', 2),
(4, 'DemoScript', 'Demo Script', 2),
(5, 'InternalSetupNotes', 'Internal Setup Notes', 2),
(6, 'FullProjectList', 'Full Project List', 1),
(9, 'PerformanceMeasuresList', 'Performance Measures List', 1),
(11, 'ProjectTypeList', 'Project Type List', 1),
(13, 'TaxonomyBranchList', 'Taxonomy Branch List', 1),
(14, 'TaxonomyTrunkList', 'Taxonomy Trunk List', 1),
(16, 'OrganizationsList', 'Organizations List', 1),
(18, 'MyProjects', 'My Projects', 1),
(22, 'ProjectMap', 'Project Map', 1),
(24, 'HomeMapInfo', 'Home Page Map Info', 2),
(25, 'HomeAdditionalInfo', 'Home Page Additional Info', 2),
(26, 'FeaturedProjectList', 'Featured Project List', 1),
(33, 'FullProjectListSimple', 'Full Project List (Simple)', 1),
(34, 'Taxonomy', 'Taxonomy', 1),
(36, 'TagList', 'Tag List', 1),
(38, 'Proposals', 'Proposals', 1),
(41, 'ManageUpdateNotifications', 'Manage Project Update Notifications', 1),
(45, 'ProposeProjectInstructions', 'Propose Project Instructions', 2),
(46, 'ProjectStewardOrganizationList', 'ProjectStewardOrganizationList', 1),
(47, 'EnterHistoricProjectInstructions', 'Enter Historic Project Instructions', 2),
(48, 'PendingProjects', 'Pending Projects', 1),
(49, 'Training','Training', 2),
(51, 'CustomFooter', 'Custom Footer', 1),
(52, 'ManageProjectCustomAttributeTypeInstructions', 'Manage Project Custom Attribute Type Instructions', 2),
(53, 'ManageProjectCustomAttributeTypesList', 'Manage Project Custom Attribute Types List', 2),
(54, 'FactSheetCustomText', 'Fact Sheet Custom Text', 2),
(55, 'FocusAreasList', 'Focus Areas List', 1),
(56, 'FullGrantList', 'Full Grant List', 1),
(57, 'FullGrantAllocationList', 'Full Grant Allocation List', 1),
(58, 'RegionsList', 'Regions List', 1),
(59, 'PriorityLandscapesList', 'Priority Landscapes List', 1),
(60, 'FullAgreementList', 'Full Agreement List', 1),
(61, 'FullInvoiceList', 'Full Invoice List', 1),
(62, 'InteractionEventList', 'Interaction/Event List', 1),
(63, 'GisUploadAttemptInstructions', 'GIS Upload Attempt Instructions', 1)

