
delete from dbo.GrantAllocationSource

insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (1, 'State', 'State', 10)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (2, 'StateGFS', 'State - GFS', 20)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (3, 'StateCapital', 'State - Capital', 30)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (4, 'StateOther', 'State - Other', 40)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (5, 'FederalWSFM', 'Federal - WSFM', 50)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (6, 'FederaNFPWUINonFedWUI', 'Federal - NFP WUI (Non-fed WUI)', 60)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (7, 'FederalCWDG', 'Federal - CWDG', 70)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (8, 'FederalLSR', 'Federal - LSR', 80)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (9, 'FederalBipartisanInfrastructureLaw', 'Federal - Bipartisan Infrastructure Law', 90)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (10, 'FederalInflationReductionAct', 'Federal - Inflation Reduction Act', 100)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (11, 'FederalConsolidatedPaymentGrant', 'Federal - Consolidated Payment Grant', 110)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (12, 'FederalCooperativeAgreements', 'Federal - Cooperative Agreements', 120)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (13, 'FederalDisasterRelief', 'Federal - Disaster Relief', 130)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (14, 'FederalForestHealthProtection', 'Federal - Forest Health Protection', 140)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (15, 'FederalForestLegacy', 'Federal - Forest Legacy', 150)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (16, 'FederalWesternBarkBeetle', 'Federal - Western Bark Beetle', 160)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (17, 'FederalFEMA', 'Federal - FEMA', 170)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (18, 'FederalBLM', 'Federal - BLM', 180)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (19, 'FederalOther', 'Federal - Other', 190)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (20, 'Private', 'Private', 200)
insert into dbo.GrantAllocationSource (GrantAllocationSourceID, GrantAllocationSourceName, GrantAllocationSourceDisplayName, SortOrder) values (21, 'Other', 'Other', 210)