USE [WADNRForestHealthDB]
GO
/****** Object:  Table [dbo].[tmptmpChildrenGrantsInGrantsTab]    Script Date: 1/16/2019 6:01:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tmpChildrenGrantsInGrantsTab]
(
	[ChildGrantID] [int] IDENTITY(1,1) not NULL,
	[Parent Child (SITKA)] [varchar](50) NULL,
	[Grant #] [varchar](50) NULL,
	[CFDA #] [varchar](50) NULL,
	[Title] [varchar](50) NULL,
	[Program Manager] [varchar](50) NULL,
	[Prog Index] [varchar](50) NULL,
	[Project Codes] [varchar](50) NULL,
	[Funding increase] [varchar](50) NULL,
	[Federal Fund Code] [varchar](50) NULL,
	[Funds Awarded] [varchar](50) NULL,
	[Matching Funds] [varchar](50) NULL,
	[Grant Total] [varchar](50) NULL,
	[DNR Match Amount] [varchar](50) NULL,
	[Non-DNR Other Match] [varchar](50) NULL,
	[Landowner Match] [varchar](50) NULL,
	[Match PI & Alpha Code] [varchar](50) NULL,
	[Expend Method] [varchar](50) NULL,
	[Start Date] [varchar](50) NULL,
	[End Date] [varchar](50) NULL,
	[Notes] [varchar](50) NULL
	CONSTRAINT [PK_tmpChildrenGrantsInGrantsTab_ChildGrantID] PRIMARY KEY CLUSTERED 
	(
		[ChildGrantID] ASC
	)
) ON [PRIMARY]
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'State Fire Assitance-Recurrent', N'John', N'214', N'---', N'', N'SPCF', N'850,000', N'850,000', N'1,700,000', N'850,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'State Fire Assitance-NFP', N'John', N'214', N'---', N'', N'SPS2', N'488,000', N'488,000', N'976,000', N'488,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'RPW', N'', N'SPUF', N'382,500', N'382,500', N'765,000', N'382,500', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Western Competitive - Urban Tech Transfer', N'Linden', N'244', N'RPY', N'', N'SPUF', N'20,000', N'20,000', N'40,000', N'20,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'      ', N'', N'SPST', N'310,000', N'310,000', N'620,000', N'310,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Ties to the Land', N'Steve G', N'25B', N'OEG', N'', N'SPST', N'75,000', N'75,000', N'150,000', N'75,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'WSFM Hazard Mitigation-SE Region CWPP', N'Steve G', N'25R', N'OFF', N'', N'SPS2', N'200,000', N'200,000', N'400,000', N'47,414', N'45,000', N'107,586', N'', N'', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'WSFM Hazard Mitigation-Ferry/Okanogan', N'Steve G & H', N'25R', N'OFB', N'', N'SPS2', N'200,000', N'200,000', N'400,000', N'47,414', N'10,000', N'142,586', N'', N'', N'7/9/2010', N'7/31/2015', N'Steve G PM/Steve H''s project area')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'WSFM Hazard Mitigation-Stevens/Pend Oreille', N'Steve G & H', N'25R', N'OEW', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'80,376', N'10,000', N'209,624', N'', N'', N'7/9/2010', N'7/31/2015', N'Steve G PM/Steve H''s project area')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'WSFM Hazard Mitigation-Spokane/Lincoln', N'Steve G & H', N'25R', N'OEK', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'80,376', N'10,000', N'209,624', N'', N'', N'7/9/2010', N'7/31/2015', N'Steve G PM/Steve H''s project area')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'NFP WUI Community Assist-Husum', N'Chuck', N'237', N'RQJ', N'', N'WFHF', N'180,000', N'181,200', N'361,200', N'0', N'10,500', N'170,700', N'', N'Staff & IPRs', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'NFP WUI Community Assist-Trout Lake', N'Chuck', N'237', N'RQK', N'', N'WFHF', N'191,232', N'201,700', N'392,932', N'0', N'31,000', N'170,700', N'', N'Staff & IPRs', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'NFP WUI Community Assist-Chumstick', N'Chuck', N'237', N'RQN', N'', N'WFHF', N'200,000', N'204,100', N'404,100', N'0', N'24,300', N'179,800', N'', N'Staff & IPRs', N'7/9/2010', N'7/31/2015', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'NFP WUI Community Assist-Greenwater', N'Jane Potter', N'237', N'RQO', N'', N'WFHF', N'77,000', N'77,000', N'154,000', N'15,800', N'7,200', N'54,000', N'', N'IPRs', N'7/9/2010', N'7/31/2015', N'PM? Funds expended')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Hazard Mit Biomass-Sherman Creek', N'Steve H', N'237', N'RQP', N'', N'SPS2', N'200,000', N'200,000', N'400,000', N'200,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'PM? Funds expended')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Hazard Mit Biomass-Aeneas Valley', N'Steve H', N'237', N'RQQ', N'', N'SPS2', N'200,000', N'200,000', N'400,000', N'200,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'PM? Funds expended')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2010-DG-11062764-010', N'10.664', N'Hazard Mit Biomass-Blue Slide', N'Steve H', N'237', N'RQR', N'', N'SPS2', N'200,000', N'200,000', N'400,000', N'200,000', N'0', N'0', N'', N'', N'7/9/2010', N'7/31/2015', N'PM? Funds expended')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'State Fire Assitance-Recurrent', N'John', N'214', N'---', N'', N'SPCF', N'700,500', N'700,500', N'1,401,000', N'700,500', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'State Fire Assitance-NFP', N'John', N'214', N'---', N'', N'SPS2', N'966,900', N'966,900', N'1,933,800', N'966,900', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'OHO', N'', N'SPUF', N'442,100', N'442,100', N'884,200', N'442,100', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'UCF Veterans', N'Linden', N'244', N'OHN', N'', N'SPUF', N'222,000', N'222,000', N'444,000', N'222,000', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'WSFM Hazard Mitigation-Firewise', N'KR', N'237', N'OHS', N'', N'SPS2', N'264,400', N'264,400', N'528,800', N'264,400', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'RFZ', N'', N'SPST', N'300,000', N'300,000', N'600,000', N'300,000', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'WSFM Hazard Mitigation-Spokane/Lincoln', N'Steve G', N'25R', N'OXC', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'109,832', N'0', N'190,168', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'WSFM Hazard Mitigation-Stevens/Pend Oreille', N'Steve G', N'25R', N'OXD', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'109,832', N'0', N'190,168', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'WSFM Hazard Mitigation-Ferry/Okanogan', N'Steve G', N'25R', N'OXE', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'109,832', N'0', N'190,168', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'WSFM Hazard Mitigation-SE Region CWPP', N'Steve G', N'25R', N'OXF', N'', N'SPS2', N'300,000', N'300,000', N'600,000', N'109,832', N'0', N'190,168', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Western Competitive Wind River-Fire', N'Steve G', N'25R', N'OIK', N'', N'SPS2', N'167,544', N'167,544', N'335,088', N'13,324', N'0', N'154,220', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Western Competitive Wind River-Stewardship', N'Steve G', N'25N', N'---', N'', N'SPST', N'132,456', N'132,456', N'264,912', N'132,456', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Western Competive Sanpoil/Kettle-Stewardship', N'Karen', N'271', N'OIQ', N'', N'SPST', N'200,000', N'300,000', N'500,000', N'200,000', N'100,000', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Western Competive Sanpoil/Kettle-Forest Health', N'Karen', N'271', N'OCL', N'', N'SPS5', N'70,000', N'70,000', N'140,000', N'70,000', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2011-DG-11062764-015', N'10.664', N'Western Competive Sanpoil/Kettle-Fire', N'Karen', N'271', N'OCM', N'', N'SPS2', N'30,000', N'30,000', N'60,000', N'30,000', N'0', N'0', N'', N'', N'8/24/2011', N'8/23/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062752-031', N'10.664', N'Turnbull', N'Myron ', N'237', N'OVS', N'', N'', N'200,000', N'0', N'200,000', N'0', N'0', N'0', N'', N'', N'8/23/2012', N'8/22/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062752-031', N'10.664', N'Tiger Highway', N'Myron ', N'237', N'OVR', N'', N'', N'76,500', N'0', N'76,500', N'0', N'0', N'0', N'', N'', N'8/23/2012', N'8/22/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062752-031', N'10.664', N'Rocky Sacheen', N'Myron ', N'237', N'OVQ', N'', N'', N'200,000', N'0', N'200,000', N'0', N'0', N'0', N'', N'', N'8/23/2012', N'8/22/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062752-031', N'10.664', N'Mazama', N'Myron ', N'237', N'OVP', N'', N'', N'200,000', N'0', N'200,000', N'0', N'0', N'0', N'', N'', N'8/23/2012', N'8/22/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'State Fire Assistance-Recurrent', N'John', N'212', N'---', N'', N'', N'545,425', N'545,425', N'1,090,850', N'545,425', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'State Fire Assistance-NFP', N'John', N'212', N'---', N'', N'', N'671,000', N'671,000', N'1,342,000', N'671,000', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'OVY', N'', N'', N'434,900', N'434,900', N'869,800', N'434,900', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Urban & Community Forestry-Inmate Education', N'Linden', N'244', N'OWA', N'', N'', N'113,000', N'113,000', N'226,000', N'113,000', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'GII', N'', N'', N'257,000', N'257,000', N'514,000', N'257,000', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'WSFM Hazard Mitigation-PCC CWPP', N'Andy T', N'237', N'"OSL, OSN, OST"', N'', N'', N'300,000', N'300,000', N'600,000', N'250,000', N'0', N'50,000', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'WSFM Hazard Mitigation-Stevens/Pend Oreille', N'Steve G', N'25R', N'OBG', N'', N'', N'300,000', N'300,000', N'600,000', N'113,159', N'0', N'186,841', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Absentee Landowner-SFA', N'Steve G', N'25B', N'OWH', N'', N'', N'60,000', N'60,000', N'120,000', N'60,000', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Absentee Landowner-FSP', N'Steve G', N'25B', N'OWG', N'', N'', N'90,000', N'90,000', N'180,000', N'90,000', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Regional Urban & Community Forestry', N'Linden', N'244', N'OWB', N'', N'', N'37,434', N'37,434', N'74,868', N'37,434', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2012-DG-11062764-018', N'10.664', N'Lower-Middle Spokane Hazardous Fuels', N'Steve H', N'237', N'OVW', N'', N'', N'82,293', N'82,293', N'164,586', N'82,293', N'0', N'0', N'', N'', N'7/24/2012', N'7/24/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-005', N'10.664', N'Chiliwist', N'Myron', N'237', N'GBC', N'', N'', N'200,000', N'0', N'20,000', N'0', N'0', N'0', N'', N'', N'8/9/2013', N'8/8/2018', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-005', N'10.664', N'East Chelan', N'Scott', N'237', N'GBD', N'', N'', N'200,000', N'182,000', N'382,000', N'2,000', N'0', N'180,000', N'', N'', N'8/9/2013', N'8/8/2018', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-005', N'10.664', N'Furport', N'Myron', N'237', N'GBE', N'', N'', N'200,000', N'0', N'200,000', N'0', N'0', N'0', N'', N'', N'8/9/2013', N'8/8/2018', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-005', N'10.664', N'Upper E Klickitat', N'Scott', N'237', N'GBF', N'', N'', N'76,500', N'92,000', N'168,500', N'2,000', N'0', N'90,000', N'', N'', N'8/9/2013', N'8/8/2018', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-005', N'10.664', N'Upper Kittitas', N'Scott', N'237', N'GBG', N'', N'', N'200,000', N'182,000', N'382,000', N'2,000', N'0', N'180,000', N'', N'', N'8/9/2013', N'8/8/2018', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'Volunteer Fire Assistance-National Fire Plan', N'', N'', N'', N'', N'', N'237,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'Phase 1', N'Darrel', N'237', N'GGM', N'', N'', N'45,831', N'45,831', N'91,662', N'', N'', N'', N'', N'', N'8/9/2013', N'12/31/2016', N'2/10/17 Close-out request submitted; 2/13/17 LuAnn')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'Phase 2', N'Darrel', N'237', N'GGN', N'', N'', N'191,169', N'191,169', N'382,338', N'', N'', N'', N'', N'', N'8/9/2013', N'12/31/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'Volunteer Fire Assistance-Recurrent', N'', N'', N'', N'', N'', N'104,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'FEPP Inventory', N'Darrel', N'237', N'GES', N'', N'', N'41,587', N'41,587', N'83,174', N'', N'', N'', N'', N'', N'8/9/2013', N'12/31/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062752-708', N'10.664', N'Phase 1', N'Darrel', N'237', N'GGO', N'', N'', N'62,413', N'62,413', N'124,826', N'', N'', N'', N'', N'', N'8/9/2013', N'12/31/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'State Fire Assistance-Recurrent', N'John', N'213', N'---', N'', N'', N'499,550', N'499,550', N'', N'499,550', N'', N'', N'', N'', N'', N'', N'final reports submitted with 2015 annual reports')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'State Fire Assistance-NFP', N'John', N'213', N'---', N'', N'', N'475,985', N'475,985', N'', N'475,985', N'', N'', N'', N'', N'', N'', N'final reports submitted with 2015 annual reports')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-Chiliwist', N'Myron', N'237', N'GBH', N'', N'', N'250,000', N'', N'', N'54,978', N'', N'245,022', N'', N'', N'', N'', N'Mod # 2 change of scope to reflect the reduction o')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-East Chelan', N'Scott', N'237', N'GBI', N'', N'', N'161,938', N'161,983', N'', N'', N'', N'161,983', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-Forker Road', N'Myron', N'237', N'GBJ', N'', N'', N'300,000', N'', N'', N'54,978', N'', N'245,022', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-Highway 195', N'Myron', N'237', N'GBK', N'', N'', N'300,000', N'', N'', N'54,978', N'', N'245,022', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-Klickitat', N'Scott', N'237', N'GBL', N'', N'', N'121,093', N'', N'', N'', N'', N'121,093', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'WSFM Hazard Mitigation-Upper Kittitas', N'Scott', N'237', N'GBO', N'', N'', N'179,999', N'', N'', N'', N'', N'179,999', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'GBN', N'', N'', N'435,000', N'435,000', N'870,000', N'435,000', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062764-706', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'GLF', N'', N'', N'253,667', N'253,667', N'507,334', N'253,667', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062765-728', N'10.680', N'Forest Health Cooperative', N'Chuck', N'271', N'GEG', N'', N'', N'224,000', N'', N'', N'224,000', N'', N'', N'270-GEG', N'', N'8/13/2013', N'12/31/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2013-DG-11062765-728', N'10.680', N'Forest Health Monitoring', N'Chuck', N'271', N'GEG', N'', N'', N'238,000', N'', N'', N'238,000', N'', N'', N'270-GEG', N'', N'8/13/2013', N'12/31/2016', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062752-742', N'10.664', N'West Klickitat', N'Scott', N'237', N'GJS', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'12/31/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062752-742', N'10.664', N'Upper Kittitas', N'Scott', N'237', N'GJT', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'12/31/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062752-742', N'10.664', N'Winthrop', N'Myron', N'237', N'GJN', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'12/31/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062752-742', N'10.664', N'Collins/Goat Pt', N'Andy', N'237', N'GKN', N'', N'', N'67,500', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'12/31/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062752-742', N'10.664', N'Gulches NFP', N'Myron', N'237', N'GJM', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'12/31/2017', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'State Fire Assistance', N'John', N'216', N'---', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'Mod #2 budget revision approved 10/20/16')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'WSFM-Bear Lake', N'Myron', N'237', N'GJO', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'WSFM-Four Mound', N'Myron', N'237', N'GJP', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'WSFM-Tum Tum', N'Myron', N'237', N'GJR', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'Volunteer Fire Assistance', N'Darrel', N'237', N'"GKB, C,D,E,G"', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'GJE', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'West Comp-Urban Forestry', N'Linden', N'244', N'GJG', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'GVJ', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2014-DG-11062765-706', N'10.664', N'West Comp-Gorge Forests', N'Chuci', N'271', N'GJX', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'7/21/2014', N'7/21/2019', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-719', N'10.680', N'Forest Health Cooperative', N'Chuck', N'271', N'GOL', N'', N'', N'101,000', N'', N'', N'101,000', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'State Fire Assistance - Recurrent', N'John', N'21B', N'XXX', N'', N'', N'1,285,000', N'2,138,396', N'3,423,396', N'', N'', N'', N'', N'', N'8/22/2015', N'8/15/2020', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'WSFM-Pingston', N'Myron', N'237', N'GVC', N'', N'', N'300,000', N'240,927', N'540,927', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'WSFM-Diamond Lake', N'Myron', N'237', N'GVD', N'', N'', N'300,000', N'240,927', N'540,927', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'Volunteer Fire Assistance', N'Darrel', N'237', N'"GVL,M,N,O,P"', N'', N'', N'460,350', N'360,350', N'820,700', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'Urban & Community Forestry', N'Linden', N'244', N'GVE', N'', N'', N'420,250', N'0', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-729', N'10.664', N'Forest Stewardship - Resource Mgmt', N'Steve G', N'25B', N'XXX', N'', N'', N'215,000', N'0', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-731', N'10.664', N'Blue Mountains (SE) ', N'Scott', N'237', N'GST', N'', N'', N'126,500', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-731', N'10.664', N'Cayuse (NE)', N'Myron', N'237', N'GSU', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-731', N'10.664', N'Chumstick (SE)', N'Scott', N'237', N'GSW', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-731', N'10.664', N'Flat-Sheep (NE)', N'Myron', N'237', N'GSX', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2015-DG-11062765-731', N'10.664', N'North Yakima (SE)', N'Scott', N'237', N'GSY', N'', N'', N'150,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'State Fire Assistance - SFA', N'John ', N'21C', N'SFA  does not require project codes only new PI ', N'', N'', N'"1,225,600 "', N'"1,225,600 "', N'"2,451,200 "', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'Volunteer Fire Assistance - VFA', N'Darrel ', N'    ', N'FEPP - RGP; Wildland Fire Training -RGR;Phase I - ', N'', N'', N'"460,500 "', N'"460,500 "', N'"921,000 "', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - Chiwawa', N'Scott', N'237', N'RGV', N'', N'', N'"300,000 "', N'"300,000 "', N'"600,000 "', N'', N'', N'"231,626 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - North Yakima', N'Scott', N'237', N'RGW', N'', N'', N'"300,000 "', N'"300,000 "', N'', N'', N'', N'"241,626 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - East Box Canyon', N'Scott', N'237', N'RGX', N'', N'', N'"300,000 "', N'"300,000 "', N'', N'', N'', N'"241,626 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - Leavenworth', N'Scott', N'237', N'RGZ', N'', N'', N'"300,000 "', N'"300,000 "', N'', N'', N'', N'"231,626 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - Upper Kettle', N'Myron ', N'237', N'RHA', N'', N'', N'"200,000 "', N'"200,000 "', N'', N'', N'', N'"162,344 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'WSFM - Clear Lake', N'Myron ', N'237', N'RHB', N'', N'', N'"300,000 "', N'"300,000 "', N'', N'', N'', N'"242,979 "', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'Urban & Community Forestry - UCF', N'Linden ', N'244', N'RHC', N'', N'', N'"388,544 "', N'"388,544 "', N'', N'', N'', N'0.00 ', N'', N'', N'', N'', N'"Mod 1: funding increase of 25,000 - 4/6/7 sent D')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'Forest Stewardship', N'Steve ', N'', N'', N'', N'', N'"215,000 "', N'"215,000 "', N'', N'', N'', N'0.00 ', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'Genetic Resources', N'Jeff DeBell', N'38F', N'RHE', N'', N'', N'"15,000 "', N'"15,000 "', N'', N'', N'', N'0.00 ', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2016-DG-11062765-729', N'10.664', N'LSR - Chehalis River Basin', N'Steve ', N'25B', N'RDO', N'', N'', N'"300,000 "', N'"300,000 "', N'', N'', N'', N'0.00 ', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'16-DG-11062765-731', N'10.664', N'Barstow', N'Myron', N'237', N'RHV', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'16-DG-11062765-731', N'10.664', N'Upper Kittitas', N'Scott', N'237', N'RHL', N'', N'', N'200,000', N'', N'', N'15,000', N'', N'160,000', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'16-DG-11062765-731', N'10.664', N'West Klickitat', N'Scott', N'237', N'RHG', N'', N'', N'191,500', N'', N'', N'15,000', N'', N'160,000', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'16-DG-11062765-731', N'10.664', N'Wauconda', N'Myron', N'237', N'RHF', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-729', N'10.664', N'State Fire Assistance - SFA', N'John K', N'', N'', N'', N'', N'1,020,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-729', N'10.664', N'Volunteer Fire Assistance - VFA', N'Darrel', N'', N'', N'', N'', N'460,268', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-729', N'10.664', N'Urban & Community Forestry - UCF', N'Linden', N'', N'', N'', N'', N'390,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-729', N'10.664', N'Forest Stewardship', N'Steve', N'', N'', N'', N'', N'215,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-729', N'10.664', N'Genetic Resources', N'Jeff', N'', N'', N'', N'', N'15,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-731', N'10.664', N'Metaline (Pend Oreille Cty)', N'Myron', N'', N'', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-731', N'10.664', N'Sawtooth (Okanogan Cty)', N'Myron', N'', N'', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-731', N'10.664', N'Horseshoe (Stevens Cty)', N'Myron', N'', N'', N'', N'', N'76,500', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-731', N'10.664', N'East Klickitat (Klickitat Cty)', N'Scott', N'', N'', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
INSERT [dbo].[tmpChildrenGrantsInGrantsTab] ([Parent Child (SITKA)], [Grant #], [CFDA #], [Title], [Program Manager], [Prog Index], [Project Codes], [Funding increase], [Federal Fund Code], [Funds Awarded], [Matching Funds], [Grant Total], [DNR Match Amount], [Non-DNR Other Match], [Landowner Match], [Match PI & Alpha Code], [Expend Method], [Start Date], [End Date], [Notes]) VALUES (N'C', N'2017-DG-11062765-731', N'10.664', N'Upper Kittitas (Kittitas Cty)', N'Scott', N'', N'', N'', N'', N'200,000', N'', N'', N'', N'', N'', N'', N'', N'', N'', N'')
GO
