
CREATE TABLE dbo.[Tmp_tmp2015-19_grant_payments_singlesheet]
	(
	tmp2015ID int NOT NULL IDENTITY (1, 1),
	BIENNIUM nvarchar(MAX) NOT NULL,
	FM_NO nvarchar(MAX) NOT NULL,
	FM_ADJ_MO nvarchar(MAX) NOT NULL,
	CAL_YEAR nvarchar(MAX) NOT NULL,
	MONTH nvarchar(MAX) NOT NULL,
	SOURCE_SYSTEM nvarchar(MAX) NOT NULL,
	DOCUMENT_NO nvarchar(MAX) NOT NULL,
	DOCUMENT_SFX_NO nvarchar(MAX) NOT NULL,
	DOCUMENT_DATE nvarchar(MAX) NOT NULL,
	DOCUMENT_INV_NO nvarchar(MAX) NOT NULL,
	INVOICE_DESCRIPTION nvarchar(MAX) NOT NULL,
	INVOICE_DATE nvarchar(MAX) NOT NULL,
	INVOICE_NO nvarchar(MAX) NOT NULL,
	GL_ACCT_CODE nvarchar(MAX) NOT NULL,
	OBJECT_CODE nvarchar(MAX) NOT NULL,
	OBJECT_NAME nvarchar(MAX) NOT NULL,
	SUB_OBJECT_CODE nvarchar(MAX) NOT NULL,
	SUB_OBJECT_NAME nvarchar(MAX) NOT NULL,
	SUB_SUB_OBJECT_CODE nvarchar(MAX) NOT NULL,
	SUB_SUB_OBJECT_NAME nvarchar(MAX) NOT NULL,
	APPROPRIATION_CODE nvarchar(MAX) NOT NULL,
	APPROPRIATION_NAME nvarchar(MAX) NOT NULL,
	FUND_CODE nvarchar(MAX) NOT NULL,
	FUND_NAME nvarchar(MAX) NOT NULL,
	ORGANIZATION_CODE nvarchar(MAX) NOT NULL,
	ORGANIZATION_NAME nvarchar(MAX) NOT NULL,
	PROGRAM_CODE nvarchar(MAX) NOT NULL,
	PROGRAM_NAME nvarchar(MAX) NOT NULL,
	PROGRAM_INDEX_CODE nvarchar(MAX) NOT NULL,
	PROGRAM_INDEX_NAME nvarchar(MAX) NOT NULL,
	SUB_PROGRAM_CODE nvarchar(MAX) NOT NULL,
	SUB_PROGRAM_NAME nvarchar(MAX) NOT NULL,
	ACTIVITY_CODE nvarchar(MAX) NOT NULL,
	ACTIVITY_NAME nvarchar(MAX) NOT NULL,
	SUB_ACTIVITY_CODE nvarchar(MAX) NOT NULL,
	SUB_ACTIVITY_NAME nvarchar(MAX) NOT NULL,
	PROJECT_CODE nvarchar(MAX) NOT NULL,
	PROJECT_NAME nvarchar(MAX) NOT NULL,
	VENDOR_NAME nvarchar(MAX) NOT NULL,
	VENDOR_NO nvarchar(MAX) NOT NULL,
	DOP_ORG nvarchar(MAX) NOT NULL,
	PERSON_DOP_ID nvarchar(MAX) NOT NULL,
	PERSON_FULL_NAME nvarchar(MAX) NOT NULL,
	EQUIP_CODE nvarchar(MAX) NOT NULL,
	EQUIP_CLASS_CODE nvarchar(MAX) NOT NULL,
	EMS_BILLING_REC_TY_CODE nvarchar(MAX) NOT NULL,
	EMS_BILLING_REC_TY_NAME nvarchar(MAX) NOT NULL,
	EQUIP_CHRG_DATE nvarchar(MAX) NOT NULL,
	NO_UNITS_SOLD nvarchar(MAX) NOT NULL,
	TRUST_CODE nvarchar(MAX) NOT NULL,
	TRUST_NAME nvarchar(MAX) NOT NULL,
	FTE_AMT nvarchar(MAX) NULL,
	EXPEND_ACCRUED nvarchar(MAX) NOT NULL,
	EQUIP_MILES_HRS_AMT nvarchar(MAX) NULL,
	AFRS_TRAN_CODE_CD nvarchar(MAX) NULL,
	CANCLD_WARRANT_IND varchar(MAX) NULL,
	AGREEMENT_YES_NO varchar(MAX) NULL,
	NUMBER_OF_UNITS varchar(MAX) NULL,
	UNIT_COST varchar(MAX) NULL,
	TAX_AMOUNT varchar(MAX) NULL,
	ADJUSTMENT_AMOUNT varchar(MAX) NULL,
	ADJUSTMENT_COMMENT varchar(MAX) NULL,
	AGREEMENT_TYPE_CODE nvarchar(MAX) NOT NULL,
	AGREEMENT_TYPE_NAME nvarchar(MAX) NOT NULL,
	RESOURCE_TYPE_CODE nvarchar(MAX) NOT NULL,
	RESOURCE_TYPE_NAME nvarchar(MAX) NOT NULL,
	UNIT_TYPE_CODE nvarchar(MAX) NOT NULL,
	UNIT_TYPE_NAME nvarchar(MAX) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.[Tmp_tmp2015-19_grant_payments_singlesheet] SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.[Tmp_tmp2015-19_grant_payments_singlesheet] ON
GO
IF EXISTS(SELECT * FROM dbo.[tmp2015-19_grant_payments_singlesheet])
	 EXEC('INSERT INTO dbo.[Tmp_tmp2015-19_grant_payments_singlesheet] (tmp2015ID, BIENNIUM, FM_NO, FM_ADJ_MO, CAL_YEAR, MONTH, SOURCE_SYSTEM, DOCUMENT_NO, DOCUMENT_SFX_NO, DOCUMENT_DATE, DOCUMENT_INV_NO, INVOICE_DESCRIPTION, INVOICE_DATE, INVOICE_NO, GL_ACCT_CODE, OBJECT_CODE, OBJECT_NAME, SUB_OBJECT_CODE, SUB_OBJECT_NAME, SUB_SUB_OBJECT_CODE, SUB_SUB_OBJECT_NAME, APPROPRIATION_CODE, APPROPRIATION_NAME, FUND_CODE, FUND_NAME, ORGANIZATION_CODE, ORGANIZATION_NAME, PROGRAM_CODE, PROGRAM_NAME, PROGRAM_INDEX_CODE, PROGRAM_INDEX_NAME, SUB_PROGRAM_CODE, SUB_PROGRAM_NAME, ACTIVITY_CODE, ACTIVITY_NAME, SUB_ACTIVITY_CODE, SUB_ACTIVITY_NAME, PROJECT_CODE, PROJECT_NAME, VENDOR_NAME, VENDOR_NO, DOP_ORG, PERSON_DOP_ID, PERSON_FULL_NAME, EQUIP_CODE, EQUIP_CLASS_CODE, EMS_BILLING_REC_TY_CODE, EMS_BILLING_REC_TY_NAME, EQUIP_CHRG_DATE, NO_UNITS_SOLD, TRUST_CODE, TRUST_NAME, FTE_AMT, EXPEND_ACCRUED, EQUIP_MILES_HRS_AMT, AFRS_TRAN_CODE_CD, CANCLD_WARRANT_IND, AGREEMENT_YES_NO, NUMBER_OF_UNITS, UNIT_COST, TAX_AMOUNT, ADJUSTMENT_AMOUNT, ADJUSTMENT_COMMENT, AGREEMENT_TYPE_CODE, AGREEMENT_TYPE_NAME, RESOURCE_TYPE_CODE, RESOURCE_TYPE_NAME, UNIT_TYPE_CODE, UNIT_TYPE_NAME)
		SELECT tmp2015ID, BIENNIUM, FM_NO, FM_ADJ_MO, CAL_YEAR, MONTH, SOURCE_SYSTEM, DOCUMENT_NO, DOCUMENT_SFX_NO, DOCUMENT_DATE, DOCUMENT_INV_NO, INVOICE_DESCRIPTION, INVOICE_DATE, INVOICE_NO, GL_ACCT_CODE, OBJECT_CODE, OBJECT_NAME, SUB_OBJECT_CODE, SUB_OBJECT_NAME, SUB_SUB_OBJECT_CODE, SUB_SUB_OBJECT_NAME, APPROPRIATION_CODE, APPROPRIATION_NAME, FUND_CODE, FUND_NAME, ORGANIZATION_CODE, ORGANIZATION_NAME, PROGRAM_CODE, PROGRAM_NAME, PROGRAM_INDEX_CODE, PROGRAM_INDEX_NAME, SUB_PROGRAM_CODE, SUB_PROGRAM_NAME, ACTIVITY_CODE, ACTIVITY_NAME, SUB_ACTIVITY_CODE, SUB_ACTIVITY_NAME, PROJECT_CODE, PROJECT_NAME, VENDOR_NAME, VENDOR_NO, DOP_ORG, PERSON_DOP_ID, PERSON_FULL_NAME, EQUIP_CODE, EQUIP_CLASS_CODE, EMS_BILLING_REC_TY_CODE, EMS_BILLING_REC_TY_NAME, EQUIP_CHRG_DATE, NO_UNITS_SOLD, TRUST_CODE, TRUST_NAME, FTE_AMT, EXPEND_ACCRUED, EQUIP_MILES_HRS_AMT, AFRS_TRAN_CODE_CD, CANCLD_WARRANT_IND, AGREEMENT_YES_NO, NUMBER_OF_UNITS, UNIT_COST, TAX_AMOUNT, ADJUSTMENT_AMOUNT, ADJUSTMENT_COMMENT, AGREEMENT_TYPE_CODE, AGREEMENT_TYPE_NAME, RESOURCE_TYPE_CODE, RESOURCE_TYPE_NAME, UNIT_TYPE_CODE, UNIT_TYPE_NAME FROM dbo.[tmp2015-19_grant_payments_singlesheet] WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.[Tmp_tmp2015-19_grant_payments_singlesheet] OFF
GO
DROP TABLE dbo.[tmp2015-19_grant_payments_singlesheet]
GO
EXECUTE sp_rename N'dbo.[Tmp_tmp2015-19_grant_payments_singlesheet]', N'tmp2015-19_grant_payments_singlesheet', 'OBJECT' 
GO
ALTER TABLE dbo.[tmp2015-19_grant_payments_singlesheet] ADD CONSTRAINT
	[PK_tmp2015-19_grant_payments_singlesheet_tmp2015ID] PRIMARY KEY CLUSTERED 
	(
	tmp2015ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

