
exec sp_rename 'FK_ProjectPersonRelationshipType_ProjectPersonRelationshipType', 'FK_ProjectPersonRelationshipType_FieldDefinition_FieldDefinitionID', 'OBJECT'
exec sp_rename 'FK_TenantAttribute_ProjectStewardshipAreaType_ProjectStewardshipAreaTypeID', 'FK_SystemAttribute_ProjectStewardshipAreaType_ProjectStewardshipAreaTypeID', 'OBJECT'
exec sp_rename 'FK_TenantAttribute_TaxonomyLevel_AssociatePerfomanceMeasureTaxonomyLevelID_TaxonomyLevelID', 'FK_SystemAttribute_TaxonomyLevel_AssociatePerfomanceMeasureTaxonomyLevelID_TaxonomyLevelID', 'OBJECT'
exec sp_rename 'FK_TenantAttribute_TaxonomyLevel_TaxonomyLevelID', 'FK_SystemAttribute_TaxonomyLevel_TaxonomyLevelID', 'OBJECT'