IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_County_CountyFeature')
                          create spatial index [SPATIAL_County_CountyFeature] on [WADNRForestHealthDB].[dbo].[County]([CountyFeature])
                          with (BOUNDING_BOX=(-125, 45, -116, 50))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_DNRUplandRegion_DNRUplandRegionLocation')
                          create spatial index [SPATIAL_DNRUplandRegion_DNRUplandRegionLocation] on [WADNRForestHealthDB].[dbo].[DNRUplandRegion]([DNRUplandRegionLocation])
                          with (BOUNDING_BOX=(-125, 45, -116, 50))
-- for [WADNRForestHealthDB].[dbo].[FocusArea].[FocusAreaLocation]
    -- No rows in table, cannot suggest index bounds: [SPATIAL_FocusArea_FocusAreaLocation]
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_ForesterWorkUnit_ForesterWorkUnitLocation')
                          create spatial index [SPATIAL_ForesterWorkUnit_ForesterWorkUnitLocation] on [WADNRForestHealthDB].[dbo].[ForesterWorkUnit]([ForesterWorkUnitLocation])
                          with (BOUNDING_BOX=(-125, 45, -116, 50))
-- for [WADNRForestHealthDB].[dbo].[GisFeature].[GisFeatureGeometry]
    -- No rows in table, cannot suggest index bounds: [SPATIAL_GisFeature_GisFeatureGeometry]
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_InteractionEvent_InteractionEventLocationSimple')
                          create spatial index [SPATIAL_InteractionEvent_InteractionEventLocationSimple] on [WADNRForestHealthDB].[dbo].[InteractionEvent]([InteractionEventLocationSimple])
                          with (BOUNDING_BOX=(-123, 47, -122, 48))
-- for [WADNRForestHealthDB].[dbo].[Organization].[OrganizationBoundary]
    -- No rows in table, cannot suggest index bounds: [SPATIAL_Organization_OrganizationBoundary]
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PclBoundaryLine_Feature')
                          create spatial index [SPATIAL_PclBoundaryLine_Feature] on [WADNRForestHealthDB].[dbo].[PclBoundaryLine]([Feature])
                          with (BOUNDING_BOX=(-121, 47, -120, 48))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PclLandscapeTreatmentPriority_Feature')
                          create spatial index [SPATIAL_PclLandscapeTreatmentPriority_Feature] on [WADNRForestHealthDB].[dbo].[PclLandscapeTreatmentPriority]([Feature])
                          with (BOUNDING_BOX=(-121, 47, -120, 48))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PclVectorRanked_Feature')
                          create spatial index [SPATIAL_PclVectorRanked_Feature] on [WADNRForestHealthDB].[dbo].[PclVectorRanked]([Feature])
                          with (BOUNDING_BOX=(-121, 47, -120, 48))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PclWildfireResponseBenefit_Feature')
                          create spatial index [SPATIAL_PclWildfireResponseBenefit_Feature] on [WADNRForestHealthDB].[dbo].[PclWildfireResponseBenefit]([Feature])
                          with (BOUNDING_BOX=(-121, 47, -120, 48))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PodVectorRanked_Feature')
                          create spatial index [SPATIAL_PodVectorRanked_Feature] on [WADNRForestHealthDB].[dbo].[PodVectorRanked]([Feature])
                          with (BOUNDING_BOX=(-121, 47, -120, 48))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_PriorityLandscape_PriorityLandscapeLocation')
                          create spatial index [SPATIAL_PriorityLandscape_PriorityLandscapeLocation] on [WADNRForestHealthDB].[dbo].[PriorityLandscape]([PriorityLandscapeLocation])
                          with (BOUNDING_BOX=(-125, 45, -117, 50))
-- for [WADNRForestHealthDB].[dbo].[Project].[DefaultBoundingBox]
    -- No rows in table, cannot suggest index bounds: [SPATIAL_Project_DefaultBoundingBox]
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_Project_ProjectLocationPoint')
                          create spatial index [SPATIAL_Project_ProjectLocationPoint] on [WADNRForestHealthDB].[dbo].[Project]([ProjectLocationPoint])
                          with (BOUNDING_BOX=(-125, 45, -117, 50))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_ProjectLocation_ProjectLocationGeometry')
                          create spatial index [SPATIAL_ProjectLocation_ProjectLocationGeometry] on [WADNRForestHealthDB].[dbo].[ProjectLocation]([ProjectLocationGeometry])
                          with (BOUNDING_BOX=(-125, 45, -117, 50))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_ProjectLocationUpdate_ProjectLocationUpdateGeometry')
                          create spatial index [SPATIAL_ProjectLocationUpdate_ProjectLocationUpdateGeometry] on [WADNRForestHealthDB].[dbo].[ProjectLocationUpdate]([ProjectLocationUpdateGeometry])
                          with (BOUNDING_BOX=(-124, 46, -117, 49))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_ProjectUpdate_ProjectLocationPoint')
                          create spatial index [SPATIAL_ProjectUpdate_ProjectLocationPoint] on [WADNRForestHealthDB].[dbo].[ProjectUpdate]([ProjectLocationPoint])
                          with (BOUNDING_BOX=(-124, 46, -117, 49))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_StateProvince_StateProvinceFeature')
                          create spatial index [SPATIAL_StateProvince_StateProvinceFeature] on [WADNRForestHealthDB].[dbo].[StateProvince]([StateProvinceFeature])
                          with (BOUNDING_BOX=(-142, 33, -102, 79))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_SystemAttribute_DefaultBoundingBox')
                          create spatial index [SPATIAL_SystemAttribute_DefaultBoundingBox] on [WADNRForestHealthDB].[dbo].[SystemAttribute]([DefaultBoundingBox])
                          with (BOUNDING_BOX=(-125, 45, -117, 50))

IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_TreatmentArea_TreatmentAreaFeature')
                          create spatial index [SPATIAL_TreatmentArea_TreatmentAreaFeature] on [WADNRForestHealthDB].[dbo].[TreatmentArea]([TreatmentAreaFeature])
                          with (BOUNDING_BOX=(-125, 45, -117, 50))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_WashingtonCounty_WashingtonCountyLocation')
                          create spatial index [SPATIAL_WashingtonCounty_WashingtonCountyLocation] on [WADNRForestHealthDB].[dbo].[WashingtonCounty]([WashingtonCountyLocation])
                          with (BOUNDING_BOX=(-125, 45, -116, 50))
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_WashingtonLegislativeDistrict_WashingtonLegislativeDistrictLocation')
                          create spatial index [SPATIAL_WashingtonLegislativeDistrict_WashingtonLegislativeDistrictLocation] on [WADNRForestHealthDB].[dbo].[WashingtonLegislativeDistrict]([WashingtonLegislativeDistrictLocation])
                          with (BOUNDING_BOX=(-125, 45, -116, 50))