ALTER TABLE GrantAllocationAwardLandownerCostShareLineItem drop column 
GrantAllocationAwardLandownerCostShareLineItemStartDate
      ,[GrantAllocationAwardLandownerCostShareLineItemEndDate]
      ,[GrantAllocationAwardLandownerCostShareLineItemFootprintAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemChippingAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemPruningAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemThinningAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemMasticationAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemGrazingAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemLopAndScatterAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemBiomassRemovalAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemHandPileAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemBroadcastBurnAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemHandPileBurnAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemMachinePileBurnAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemOtherTreatmentAcres]
      ,[GrantAllocationAwardLandownerCostShareLineItemSlashAcres]