SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tmp2015-19_grant_payments_singlesheet](
	[tmp2015ID] [int] IDENTITY(1,1) NOT NULL,
	[BIENNIUM] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FM_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FM_ADJ_MO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CAL_YEAR] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MONTH] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SOURCE_SYSTEM] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DOCUMENT_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DOCUMENT_SFX_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DOCUMENT_DATE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DOCUMENT_INV_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INVOICE_DESCRIPTION] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INVOICE_DATE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INVOICE_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[GL_ACCT_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OBJECT_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OBJECT_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_OBJECT_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_OBJECT_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_SUB_OBJECT_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_SUB_OBJECT_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[APPROPRIATION_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[APPROPRIATION_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FUND_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FUND_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ORGANIZATION_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ORGANIZATION_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROGRAM_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROGRAM_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROGRAM_INDEX_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROGRAM_INDEX_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_PROGRAM_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_PROGRAM_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ACTIVITY_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ACTIVITY_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_ACTIVITY_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SUB_ACTIVITY_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROJECT_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROJECT_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VENDOR_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VENDOR_NO] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DOP_ORG] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PERSON_DOP_ID] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PERSON_FULL_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EQUIP_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EQUIP_CLASS_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EMS_BILLING_REC_TY_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EMS_BILLING_REC_TY_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EQUIP_CHRG_DATE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NO_UNITS_SOLD] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRUST_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRUST_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FTE_AMT] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPEND_ACCRUED] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EQUIP_MILES_HRS_AMT] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AFRS_TRAN_CODE_CD] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CANCLD_WARRANT_IND] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGREEMENT_YES_NO] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMBER_OF_UNITS] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIT_COST] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAX_AMOUNT] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADJUSTMENT_AMOUNT] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADJUSTMENT_COMMENT] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGREEMENT_TYPE_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AGREEMENT_TYPE_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RESOURCE_TYPE_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RESOURCE_TYPE_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UNIT_TYPE_CODE] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UNIT_TYPE_NAME] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_tmp2015-19_grant_payments_singlesheet_tmp2015ID] PRIMARY KEY CLUSTERED 
(
	[tmp2015ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
