SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoaRawSoutheast](
	[LoaRawSoutheastID] [int] IDENTITY(1,1) NOT NULL,
	[Project ID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Last Name] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[First Name] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Application Date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Decision Date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[County] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester Phone] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester email] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total Acres] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fund Source] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Allocated Amount] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Letter Date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Project Expiration Date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stewardship Plan y/n] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Percent Match] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treatment 6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Acres 6] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total Max] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_per_acre] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City, St, Zip] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 1 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 2 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 3 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 4 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coordinator] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treated Acres] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Contractor?] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Name 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Name 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Address 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Address 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Number] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Grant #] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Invoice #] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Invoice Date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fund] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Appn] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Grant] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Index] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sub] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Org] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Match] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Pay] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total Spent] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Actual Spent] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coordinator Email] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coordinator #] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TH] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RX] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Reconciled in Grant tracker] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comments in grant tracker] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[1/20/2021 10:06] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[True Allocation] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Agreement Contract Number] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_LoaRawSoutheast_LoaRawSoutheastID] PRIMARY KEY CLUSTERED 
(
	[LoaRawSoutheastID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
