SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FederalFundCode](
	[FederalFundCodeID] [int] IDENTITY(1,1) NOT NULL,
	[FederalFundCodeAbbrev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FederalFundCodeProgram] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_FederalFundCode_FederalFundCodeID] PRIMARY KEY CLUSTERED 
(
	[FederalFundCodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
