SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tmpGrantAllocationsFlatFile](
	[AREA] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Region] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FH_FP_WD_LG] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[A_B_C_D] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FED_APPROP] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CFDA] [float] NULL,
	[Status] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Funding_Source_or_Grant_Number] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Start_Date] [datetime2](7) NULL,
	[End_Date] [datetime2](7) NULL,
	[Program_Index_PI] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Grant_Project_Name] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_Award] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[13_15_BN_Spent] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[15_17_BN_Spent] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_spent_as_of_6_30_17_per_270_BNs_13_15_15_17_] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[17_19_BN_Spent_as_of_3_31_2018] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Spent_over_all_B_N] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Current_Balance] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Spent_to_date_X_check] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Set_Aside_for_Future_BN] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Current_Balance_minus_setaside_for_future_B_N] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Personnel] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fringe_Benefits] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Travel] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Supplies] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Contractual] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Indirect] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Actual_To_Date] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_across] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Match_Committed] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Match_DNR] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Match_Other] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Match_Match] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Notes] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
