SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoaRawNortheast](
	[LoaRawNortheastID] [int] IDENTITY(1,1) NOT NULL,
	[Project ID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Last Name] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[First Name] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Application Date] [datetime] NULL,
	[Decision Date] [datetime] NULL,
	[County] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester Phone] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Forester email] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total Acres] [float] NULL,
	[Status] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fund Source] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Letter Date] [datetime] NULL,
	[Project Expiration Date] [datetime] NULL,
	[Stewardship Plan y/n] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Percent Match] [float] NULL,
	[Treatment 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost1] [money] NULL,
	[$/ac 1] [money] NULL,
	[Acres 1] [float] NULL,
	[Treatment 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost2] [money] NULL,
	[$/ac 2] [money] NULL,
	[Acres 2] [float] NULL,
	[Treatment 3] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost3] [money] NULL,
	[$/ac 3] [money] NULL,
	[Acres 3] [float] NULL,
	[Treatment 4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost4] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 4] [money] NULL,
	[Acres 4] [float] NULL,
	[Treatment 5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cost5] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[$/ac 5] [money] NULL,
	[Acres 5] [float] NULL,
	[Total Max] [money] NULL,
	[Address] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City, St, Zip] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 1 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 2 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 3 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment 4 w/date] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Coordinator] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Treated Acres] [float] NULL,
	[Contractor?] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Name 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Name 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Address 1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Address 2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Vendor Number] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Grant #] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Invoice #] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Invoice Date] [datetime] NULL,
	[Fund] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Appn] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Grant] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Code] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Index] [float] NULL,
	[Sub] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Org] [float] NULL,
	[Match] [money] NULL,
	[Pay] [money] NULL,
 CONSTRAINT [PK_LoaRawNortheast_LoaRawNortheastID] PRIMARY KEY CLUSTERED 
(
	[LoaRawNortheastID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
